### ISSUE TITLE
HTTP 500 on /tokenize

### ISSUE THREAD

**Issue by cocoche007** [GBSEcom/paymentjs-integration-nodejs#12]
Hi, 

I tried the sample project of https://github.com/GBSEcom/paymentjs-integration-nodejs.
But when I click on Pay, I've an error.
The authorize-session is OK and provide to me a token and a public key.
But the process fails on the POST on /tokenize ("failed to contact merchant server").

I'm sure of the config.json file because works on another project.

My node is 12.13.1 (and I tested without success on 8.1.1).

**Comment by milindjoshi7705** [comment]
Did you get any solution for this? I am also facing same error.

**Comment by brandon-garcia** [comment]
Hello, thanks for reaching out. Sorry for the long wait, we dont typically monitor these example repositories.

To start with, if this is a new integration you might want to get in contact with our integration support team. For confirmed working integrations that suddenly start getting an issue feel free to open an incident through the proper channels.

Since session authorization is working that tells me you have registered credentials. These credentials are supposed to have a webhook url associated with them where the actual results of tokenization get forwarded to.

There's a few possibilities:
- you are not fully boarded. There is a manual process on our side to complete boarding which involves configuring this webhook url for your credentials. If this is the case please submit this form and maybe let your account representative know if there is no followup: https://docs.paymentjs.firstdata.com/form/integration
- your configured webhook is incorrect. If this is the case you can follow the same approach as the previous suggestion.
- your configured webhook is not responding correctly or we cant reach it. Webhooks must be https endpoints that are accessible over the open internet via the HTTP POST method and HTTP error response cods are reported back to the browser as a 500 (so return 200 status for success scenarios). The documentation shows example webhook requests including headers here: https://docs.paymentjs.firstdata.com/#webhook

For securing these endpoints there are a few options:
- ip whitelisting: integration support team can advise here but this may likely be overkill and could be a brittle integration
- Pass a strong Nonce header value when authorizing the session (uuid or timestamp wouldnt be very strong) and then verify the Nonce header matches when it comes back through the webhook at the tail end of the tokenization flow.
- reject webhook requests for Client-Token header values you did not authorize
