### ISSUE TITLE
Could you add the code to show how you recommend doing step 14?

### ISSUE THREAD

**Issue by burtontanner** [GBSEcom/paymentjs-integration-nodejs#6]
![c9270d60dcedbcf01a40c34e482f9f07](https://user-images.githubusercontent.com/10554651/76010139-a5230b80-5ecf-11ea-910a-4d631dc9346e.png)

**Comment by brandon-garcia** [comment]
We've implemented this in https://github.com/GBSEcom/pjsv2_example

specifically most of the code for this is in https://github.com/GBSEcom/pjsv2_example/blob/master/src/client/webhook.ts

Apologies ahead of time for the messiness of the code, I've been meaning to update that repo to make it easier to follow and understand.

since the browser doesn't get a response from the api until after the webhook data is delivered, polling a webhook status check endpoint on the server side is an option since it won't be polling very many times (1-2 times in my experience). To poll, have the browser call an endpoint repeatedly on your backend server that checks if the webhook data has been received (this can be correlated with the client token for example), if the webhook data has been received then you can call another endpoint that checks if the tokenization was successful or unsuccessful. These two endpoints could of course be combined into one but they are separated out in pjsv2_example because we wanted our quality assurance team to be able to view the webhook data from the browser (note that sending the full webhook data to the browser is very much discouraged in production due to a large risk of facilitating fraudulent cardrunning activities)

I'll consider implementing this functionality in this repo as well since it is an important part of the flow

**Comment by burtontanner** [comment]
@brandon-garcia Thanks! I ended up using web sockets, But was mostly curious what the recommended approach was.
